export const HELP_HTML = `
<p>Starforge is a 1:1 Earth and Moon with real orbital mechanics. Build a ship in the hangar, take off from any real airport, reach orbit, fly to the Moon, land, and come home.</p>
<h3>First flight</h3>
<p>Pick the <b>Kestrel</b> jet, choose any airport and a runway, then push the throttle all the way up. At about 75 m/s (150 kt) pull back on the stick to lift off. Raise the gear. Fly anywhere — the whole planet is real satellite imagery with real terrain and buildings.</p>
<h3>Flying</h3>
<p><b>Assisted</b> flight (default) is fly-by-wire: the stick commands g-load and roll rate; let go and the ship holds its climb angle and bank. Turns are coordinated automatically and the computer won't let you stall. <b>Realistic</b> (Settings) gives you raw control surfaces.</p>
<p>Touch: left stick = pitch and roll, the bar under it = rudder / nose-wheel steering, right slider = throttle. Drag the sky to look around, pinch to zoom.</p>
<p>Keyboard: <kbd>W</kbd>/<kbd>S</kbd> pitch, <kbd>A</kbd>/<kbd>D</kbd> roll, <kbd>Q</kbd>/<kbd>E</kbd> yaw, <kbd>Shift</kbd>/<kbd>Ctrl</kbd> throttle, <kbd>Z</kbd> full, <kbd>X</kbd> cut, <kbd>G</kbd> gear, <kbd>B</kbd> brakes (hold), <kbd>T</kbd> SAS on/off, <kbd>1</kbd>–<kbd>8</kbd> SAS modes, <kbd>R</kbd> RCS, <kbd>V</kbd> engine group, <kbd>F</kbd> hybrid mode, <kbd>U</kbd> lights, <kbd>O</kbd> info panel, <kbd>M</kbd> map, <kbd>C</kbd> camera, <kbd>,</kbd>/<kbd>.</kbd> time warp, <kbd>P</kbd> autopilot, <kbd>Esc</kbd> pause. In space, RCS thrusters translate: <kbd>H</kbd>/<kbd>N</kbd> forward/back, <kbd>J</kbd>/<kbd>L</kbd> left/right, <kbd>I</kbd>/<kbd>K</kbd> up/down. Gamepads work too.</p>
<h3>Going to space</h3>
<p>Air-breathing jets stop working high up. Spaceplanes like <b>Selene</b> take off on jets, then light the fusion torch. Watch the <b>navball</b>: the yellow circle is where you're moving (prograde). To make orbit you need about 7.8 km/s sideways above 140 km. Easiest: open <b>Autopilot → Ascend to orbit</b>.</p>
<h3>Meridian Station</h3>
<p>A crewed station circles the Earth at 420 km, tilted 51.6° to the equator. Dock there and you can fill every tank for free. Ships need a <b>docking port</b> and <b>RCS thrusters</b> to dock (Selene and Starhopper have both).</p>
<p>The easy way: on the runway or launch pad, tap <b>Autopilot → Fly to Meridian Station</b>. It waits for the station's orbit to pass overhead (time warp runs by itself), climbs into its plane, matches planes, transfers, brakes a kilometre behind it and docks. From orbit, the same item (or the map's <b>Autopilot: rendezvous and dock</b>) does everything but the launch.</p>
<p>By hand: in the map, <b>Match planes</b>, then <b>Intercept</b>; the green labels show the closest approach. Then <b>Match speed at closest approach</b>. Close in, the HUD brackets the station, the speed readout switches to <b>TGT</b> (speed relative to it) and the navball shows green markers: the square points at the station, the circles are your velocity toward and away from it (SAS <b>Stn</b>, <b>T+</b>, <b>T−</b>). Kill the drift on T−, point at the port and creep in on RCS below 0.8 m/s — the ports latch when they meet. Or just tap <b>Dock</b> (<kbd>Y</kbd>) within a few kilometres. <b>Undock</b> backs you away to a safe distance. Bumping the station gently is harmless; ramming it is not.</p>
<h3>The Moon</h3>
<p>The easy way there: <b>Autopilot → Fly me to the Moon…</b> and pick a landing site (or just lunar orbit). From a runway or pad it climbs to orbit first, then flies the transfer, a correction on the way, the capture, and lands on the spot — waiting in orbit, warped, until the Moon turns the site underneath. A few days of game time; at full warp, a minute or two.</p>
<p>In orbit, open the <b>map</b> (◍) and tap <b>Go to the Moon</b>. The computer simulates the real burn and finds a transfer; tap <b>Autopilot</b> (or <b>Warp to it</b>) to fly it. On the way, <b>Fine-tune Moon approach</b> plans a small correction — it picks the cheapest moment, which may be hours later. Near the Moon tap <b>Capture into lunar orbit</b>, then <b>Autopilot: land on the Moon</b>: it deorbits, coasts (warping automatically), fires a braking burn and touches down on the belly thrusters.</p>
<p>The easy way back: in the map tap <b>Autopilot: fly me home…</b> and pick an airport (the one you took off from is at the top). The autopilot takes off if you're landed, leaves lunar orbit lined up with that airport, corrects course on the way, brakes into Earth orbit and lands — time warp runs by itself in between. It takes a few days of game time; at full warp, a few minutes.</p>
<p>By hand: <b>Autopilot → Take off to lunar orbit</b>, then <b>Return to Earth orbit</b> in the map. Spaceplanes come back into Earth orbit with a braking burn at periapsis — a straight dive in at 11 km/s is right at the limit of what wings survive. Ships with a heat shield can go direct.</p>
<h3>Coming home</h3>
<p>From Earth orbit, open the map and tap <b>Fly home to an airport…</b>, pick a city, then <b>Fly me home</b>. The autopilot waits for the right pass, burns, flies a belly-first reentry steering toward the airport, then lines up and lands on the runway. Any time you're flying a plane, <b>Autopilot → Land at …</b> lands on the nearest big runway. Move the stick to take over at any moment.</p>
<p>Tail-sitting starships like <b>Starhopper</b> tap <b>Land at an airport…</b> instead: they fall engines-first (the air does most of the braking), trim the fall with short burns, fire a landing burn near the ground and hover across to the exact spot. If the orbit doesn't pass close to the airport, the deorbit burn swings it sideways — which costs fuel, or waits for a better pass.</p>
<h3>Launch pads</h3>
<p>Rockets start from a pad beside any airport's runway — or pick <b>Launch → Pad</b>, search any city, and choose <b>Build a launch pad at…</b> to launch from right there (on the sea it floats like a barge).</p>
<h3>Views</h3>
<p>The camera button cycles chase, cockpit, free (turns with the ship) and <b>fly-by</b>, which stands beside your flight path and watches you pass. Low over the ground you'll see roads, rivers and lakes from OpenStreetMap; above about 80 km the stars come out even in daylight. Below 10 km the weather you saw from space is there in 3D — cumulus decks you can fly over, under and through (the view whites out inside one).</p>
<p>Flying a rocket by hand, coast up out of the air and the HUD offers to <b>circularize at apoapsis</b> — one tap plans and flies the burn.</p>
<h3>Heat and damage</h3>
<p>Coming back from space at 7–11 km/s heats your ship. Fly belly-first at a high angle of attack so the heat-tiled underside and heat shields take it. Parts that overheat burn away. Landing too hard breaks gear; hitting the ground or a building destroys the ship. Fusion drives also run hot — bring radiators.</p>
<p>Wings have a structural limit too: pull too many g (or bend them hard at high speed) and they snap off. The hangar shows the load each design's wings can take (<b>Wings break at</b>), Assisted flight keeps you inside it, and an <b>OVERSTRESS</b> warning flashes when you're close. Thick, broad wing roots are strong; long slender spans are not. Settings → Airframe limits turns this off.</p>
<h3>Building</h3>
<p>In the hangar, pick a part and tap on your ship to attach it. Parts snap to the ends of other parts or stick to their surfaces; symmetry mirrors them to the other side. Keep the centre of lift (blue) just behind the centre of mass (yellow) and your plane will be stable. Put the main wheels a little behind the centre of mass and spread them wide.</p>
<p>Tap a wing, tail or canard to reshape it: stretch the span, change the chord at the root and tip, and set the sweep. Long thin wings glide and climb well; short, sharply swept wings are lighter and better at high Mach. A bigger wing lands slower but weighs more. Less sweep moves the lift forward, so watch the stability check.</p>
<p>The <b>Mission check</b> under the stats tells you what a design can do — take off, reach orbit, dock at the station, land on the Moon and come home, survive reentry — with the delta-v it has against what each trip needs.</p>
<p>Some parts to try: the <b>Raptor</b> turbojet's afterburner lights over 90 % throttle (60 % more thrust, very thirsty). The <b>ion drive</b> sips xenon at Isp 6,000 s but needs 1.5 MW — carry a <b>fission reactor</b> or <b>fusion power core</b> (and a radiator), or it stalls when the batteries run flat. A <b>lifting body</b> fuselage flies without wings. Heat shields carry <b>ablator</b> that burns away on each hot reentry (the station tops it up). The <b>Bastion</b> armored pod survives 25 m/s landings. <b>Cryo tanks</b> feed the hydrolox <b>Hydra</b> (Isp 455 s) but their hydrogen boils off slowly. The <b>Ember</b> antimatter torch is the endgame drive — its <b>antimatter cell</b> needs 40 kW every second of every day, so never let the batteries run flat. The <b>swing wing</b> spreads for landing and sweeps back by itself past Mach 0.8. Paint has decals and a glow trim.</p>
<p><b>Share a ship</b>: Ships → Share gives a short code and a link; anyone can paste the code (Ships → Import) or open the link to get your design.</p>
<h3>Data</h3>
<p>Satellite imagery © EOX IT Services (Sentinel-2 cloudless, CC BY-NC-SA 4.0) and NASA GIBS. Terrain: Mapzen Terrarium / AWS Open Data. Buildings © OpenStreetMap contributors via OpenFreeMap. Airports: OurAirports (public domain). Moon imagery: NASA/LRO via Moon Trek; Moon elevation: NASA LRO/LOLA. Cities: GeoNames (CC BY).</p>
`;
